package com.example.authapp.domain.risk.entity;

public enum RiskEventType {
    LOGIN_FAILURE_BURST,
    LOCKED_ACCOUNT_LOGIN_ATTEMPT,
    DISABLED_ACCOUNT_LOGIN_ATTEMPT,
    ADMIN_LOGIN_FAILURE,
    LOGIN_RISK,
    NEW_IP_LOGIN,
    NEW_USER_AGENT_LOGIN,
    NIGHT_LOGIN,
    TOKEN_RISK,
    TOKEN_REUSE,
    TOKEN_CONTEXT_CHANGED,
    TOKEN_RAPID_CONTEXT_CHANGE,
    TOKEN_HARD_EXPIRED_USED,
    TOKEN_RECENT_ROTATION_RECOVERY
}
