package com.example.authapp.domain.audit.entity;

public enum AdminActionType {
    LOCK_USER,
    UNLOCK_USER,
    DISABLE_USER,
    ENABLE_USER,
    PASSWORD_RESET,
    MFA_RESET,
    MFA_EXCEPTION_CREATED,
    MFA_EXCEPTION_REVOKED,
    MFA_POLICY_UPDATED,
    TOKEN_REVOKE,
    ROLE_CHANGE,
    DEPARTMENT_CHANGE,
    PROFILE_UPDATE,
    DEPARTMENT_CREATE,
    DEPARTMENT_UPDATE,
    DEPARTMENT_DISABLE,
    GROUP_CREATE,
    GROUP_UPDATE,
    GROUP_DISABLE,
    GROUP_MEMBER_ADD,
    GROUP_MEMBER_REMOVE,
    GROUP_ROLE_ASSIGN,
    GROUP_ROLE_REMOVE
}
